name: cypress-todo-project

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
           record: true
        env:
         CYPRESS_RECORD_KEY: a9ce5210-dfc2-4d16-838f-d3fb6539ec0f    
